version: '2.2'
services:
  tb-gateway:
    restart: always
    image: "testgatew"
    # Ports (Required for REST connector)
    ports:
      - "5000:5000"
    volumes:
      - ~/.tb-gateway/config:/thingsboard_gateway/config
      - ~/.tb-gateway/logs:/thingsboard_gateway/logs
      - ~/.tb-gateway/extensions:/thingsboard_gateway/extensions